// Generated by Wrangler on Thu Aug 01 2024 11:50:28 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
    CF_BEARER_TOKEN: string;
    CF_ACCOUNT_ID: string;
    SENTRY_DSN: string;
    WEB_COUNTER_AE: AnalyticsEngineDataset;
}
